#+TITLE: Random notes by Org-mode 2019-02
#+AUTHOR: [[https://wangcc.me][Chaochen Wang]]
#+EMAIL: chaochen@wangcc.me
#+OPTIONS: d:(not "LOGBOOK") date:t e:t email:t f:t inline:t num:t
#+OPTIONS: timestamp:t title:t toc:t todo:t |:t

* Therneau, Terry, Cynthia CrowsonとElizabeth Atkinson. 「Using Time Dependent Covariates and Time Dependent Coeﬃcients in the Cox Model」, 日付なし, 27.

1. Page 4: One common question with this data setup is whether we need to worry about correlated data, since a given subject has multiple observations. The answer is no, we do not. The reason is that this representation is simply a programming trick. The likelihood equations at any time point use only one copy of any subject, the program picks out the correct row of data at each times. There are two exceptions to this rule: 

*** When subjects have multiple events, then the rows for the events are correlated within subject and a cluster variance is needed. 
*** When a subject appears in overlapping intervals. This however is almost always a data error, since it corresponds to two copies of the subject being present in the same strata at the same time, e.g. she could meet herself at a party. 

* pdf-tools (https://github.com/politza/pdf-tools) within the Emacs is good for annoation and reading pdf files
* CFA
** Factor Rotation (P27-)
*** Once the appropriate number of factors has been determined, the extracted factors are rotated, to foster their **intepretaibility**.

*** For any given multiple-factor model, there exist an infinite number of equally good-fitting solutions (each represented by a different factor loading matrix)

*** In applied research, factor loadings greater than or equal to 0.30 or 0.40 are often interpreted as salient (i.e. the indicator is meaningfully related to a primary or secondary factor). 

*** For models that contain two or more factors, rotation is conducted to produce a solution with **the best simple structure.** 

*** It is important to emphasize that rotation does not alter the fit of the solution. Rather, factor rotation is a mathematical transformation that is undertaken to foster interpretability by maximizing larger factor loadings closer to one and minimizing smaller factor loadings closer to zero. 

*** Constraining factors to be uncorrelated in CFA will typically result in poor model fit. 

*** Conceptually, a factor score is the score that would have been observed for a person if it had been possible to measure the factor directly. 

*** Specifically, a correlation matrix is used as input in EFA, and both the factors and indicators are completely standardized regression coefficients. 

*** Although CFA also produces a completely standardized solution, much of the analysis does not standardize the latent or observed variables. 

*** A covariance can be calculated by multiplying the correlation of the two indicators by their standard deviations, i.e., $COV_{xy} = r_{xy}SD_xSD_y$

*** SEM methodogolists often express a strong preference for reporting unstandardized solutions because the analysis itself is based on unstandardized variables, and completely standardized values are potentially misleading. 


*** For instance, the true nature of the variance and relationships among indicators and factors can be masked when these variables have been standardized; when the original matric of variables is expressed in meaningful units, unstandardized estimates more clearly convey the importance or substantive significance of the effects. 

*** All indicators in EFA freely load on all factors, and the solution is rotated to maximize the magnitude of primary loadings and minimize the magnitude of cross-loadings. 

*** Factor rotation does not apply to CFA. This is because the identification restrictions associated with CFA are achieved in part by **fixing most or all indicator cross-loadings to zero**.

*** The communality is the sum of squared factor loadings for a given indicator across all factors. 
** Parameters of a CFA model
Factor loadings are the regression slopes for predicting the indicators from the latent variable. 

** CFA model indentification (P53)
In order to estimate the parameters in CFA, the measurement model must be identified. A model is identified if, on the basis of known information (i.e., the variances and covariances in the sample input matrix).

In the first and by far the more popular method, the researcher fixes the metric of the latent variable to be the same as one of its indicators "marker or reference indicator".

In the seconde method, the variance of the latent variable is fixed to a specific value, usually 1.00. However, this method is used less often than the marker indicator approach. 

The former strategy produces an unstandardized solution (in addition to a completely standardized solution), which is useful for several purposes, such as tests of measurement invariance across groups and evaluations of scale reliability.

Unlike just-identified models, overidentified models rarely fit the data perfectly (i.e., a perfectly fitting model is one whose parameter estimates recreate the data perfectly). 

Specification of a model to have at least 0 df is a necessary but not sufficient condition for indentification.

For these and other reasons, methodologists recommend that latent variables be defined by a minimum of three indicators to avoid this possible source of underidentification. 

* Onyx: A graphical interface for Structural Equation Modeling
 http://onyx.brandmaier.de/what-is-onyx/

* Org-mode-tutorials: http://pragmaticemacs.com/org-mode-tutorials/

* Illustrating the impact of a time-varying covarate with and extended Kaplan-Meier Estimator

For example it may be reasonable to assume that the risk of ESRD (end stage renal disease) is a function of the patient's current value of serum creatinine and, conditional on that value, is not related to any previous values. 

... 

One special type of time-varying covariate deserves attention. During follow-up certain intervening events may occur which can irreversibly alter the patient's risk of the endpoint of interest. For example, the patient might suffer a stroke or permanently discontinue study medication. The covariates representing these intervening events can only take the value 0 or 1, and an individual's covariate value cannot change from 1 to 0 during the course of the trial. 

... 

By accounting for the time-varying nature of the covariates, the result should be an illustration of the expected probability of having had an event, as a function of time, for hypothetical cohorts of patients with constant covariate values over time. 

... 

**** $n$ = the total sample size
**** $Y_i$ = the follow-up time
**** $\delta_i$ = an event indicator (1 if the patient had an event at time $Y_i$)
**** $i$ is a patient indicator (patient ID)

...

Approach 1. The Final Covariate Value (comes from the Heart Outcomes Prevention Evaluation, HOPE study). This approach is clearly inconsistent with the Cox regression model, since the Cox model makes use of the patients' covariate value at each event time. 

... 


The extended Kaplan-Meier estimator recommended here simply updates the cohorts at each event time. 
* Rajkomar, Alvin, Jeffrey DeanとIsaac Kohane. 「Machine Learning in Medicine」. New England Journal of Medicine 380, no. 14 (2019年4月4日): 1347–58. https://doi.org/10.1056/NEJMra1814259.
Machine learning is not just a new tool, such as a new drug or medical device. Rather, it is the fundamental technology required to meaningfully process data that exceed the capacity of the human brain to comprehend. 
